spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/yygh_cmn?serverTimezone=GMT%2B8
          username: root
          password: 123456
        slave_1:
          url: jdbc:mysql://localhost:3307/yygh_cmn?serverTimezone=GMT%2B8
          username: root
          password: 123456
        slave_2:
          url: jdbc:mysql://localhost:3308/yygh_cmn?serverTimezone=GMT%2B8
          username: root
          password: 123456
