spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/yygh_cmn?serverTimezone=GMT%2B8
          username: root
          password: 123456
        slave_1:
          url: jdbc:mysql://localhost:3307/yygh_cmn?serverTimezone=GMT%2B8
          username: root
          password: 123456
        slave_2:
          url: jdbc:mysql://localhost:3308/yygh_cmn?serverTimezone=GMT%2B8
          username: root
          password: 123456

  redis:
    database: 0
    timeout: 1800000
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
      max-redirects: 3
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
        max-wait: -1

